### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Hellowlol** [alyakhtar/Katastrophe#10]
Can you add support for slice so i can do `::` to download them all?

**Comment by alyakhtar** [comment]
hey @Hellowlol, I have added the feature u requested for. The feature works just like the slice system in python, you can give the input as i,j - where it will use the starting serial no (i) and ending serial no (j) to download all the files between them or u can use i, and ,i. You can also now download multiple files by passing their serial numbers (eg 1,2,3,4).
