### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by mykahveli** [alyakhtar/Katastrophe#15]
![deepinscreenshot20160630004351](https://cloud.githubusercontent.com/assets/19893245/16472455/0786f810-3e5c-11e6-8dbd-41b231ef4c0a.png)

**Comment by alyakhtar** [comment]
@mykahveli   Please update and use --verifyssl=false option

```
 $katastrophe --verifyssl=false
 $katastrophe --verifyssl=false -m
 $katastrophe --verifyssl=false -T 
```
