### ISSUE TITLE
cannot install on ubuntu 16.04

### ISSUE THREAD

**Issue by sugionodjojo** [alyakhtar/Katastrophe#16]
hello,

this is what i got on my terminal when trying to install katastrophe

Failed building wheel for lxml
Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: bencode, bitstring, docopt, lxml, katastrophe
Exception:
Traceback (most recent call last):
File “/home/sugiono/.local/lib/python2.7/site-packages/pip/basecommand.py”, line 215, in main
status = self.run(options, args)
File “/home/sugiono/.local/lib/python2.7/site-packages/pip/commands/install.py”, line 317, in run
prefix=options.prefix_path,
File “/home/sugiono/.local/lib/python2.7/site-packages/pip/req/req_set.py”, line 742, in install
**kwargs
File “/home/sugiono/.local/lib/python2.7/site-packages/pip/req/req_install.py”, line 831, in install
self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
File “/home/sugiono/.local/lib/python2.7/site-packages/pip/req/req_install.py”, line 1032, in move_wheel_files
isolated=self.isolated,
File “/home/sugiono/.local/lib/python2.7/site-packages/pip/wheel.py”, line 346, in move_wheel_files
clobber(source, lib_dir, True)
File “/home/sugiono/.local/lib/python2.7/site-packages/pip/wheel.py”, line 317, in clobber
ensure_dir(destdir)
File “/home/sugiono/.local/lib/python2.7/site-packages/pip/utils/**init**.py”, line 83, in ensure_dir
os.makedirs(path)
File “/usr/lib/python2.7/os.py”, line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 13] Permission denied: ‘/usr/local/lib/python2.7/dist-packages/bencode’

are there any easy way to install? thanks

**Comment by sugionodjojo** [comment]
hello,

i try with sudo , and it went through, though there some warning that shell and wheel was not belong to the user and should use sudo -H

and now when I input katastrophe -M on terminal, it return
Torrent Search :  donnie darko
Traceback (most recent call last):
  File "/usr/local/bin/katastrophe", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/katastrophe.py", line 222, in main
    categories(0)
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/subcategories.py", line 603, in categories
    table = getattr(sys.modules[**name**], 'by_%s' % category_list[category])(query, page)
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/subcategories.py", line 112, in by_movies
    source_code = requests.get(link)
  File "/home/sugiono/.local/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/sugiono/.local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/home/sugiono/.local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/sugiono/.local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, *_kwargs)
  File "/home/sugiono/.local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL] unknown error (_ssl.c:590)

what went wrong? please advise. thanks.

**Comment by alyakhtar** [comment]
@sugionodjojo  Please update and use --verifyssl=false option

```
 $katastrophe --verifyssl=false
 $katastrophe --verifyssl=false -m
 $katastrophe --verifyssl=false -T 
```

**Comment by sugionodjojo** [comment]
hello,

it is not working, it return with 

Usage:
  katastrophe
  katastrophe [-m | -t | -a | -s | -l | -g | -p | -b | -x | -M | -T | -A | -S | -B | -G | -P | -X]
  katastrophe -h | --help
  katastrophe --version  
  Multi Download:
    i,j     From Serial No. i to Serial No. j
    ,i      From Serial No. 1 to Serial No. i 
    i,      From Serial No. i to serial no 25
    i,j,... Multiple Serial Numbers

**Comment by sugionodjojo** [comment]
and katastrophe version is 2.0.3
