### ISSUE TITLE
--verifyssl=false

### ISSUE THREAD

**Issue by sugionodjojo** [alyakhtar/Katastrophe#17]
hello,

it still not working.

when i type katastrophe --verifyssl=false, it return

Usage:
  katastrophe
  katastrophe [-m | -t | -a | -s | -l | -g | -p | -b | -x | -M | -T | -A | -S | -B | -G | -P | -X]
  katastrophe -h | --help
  katastrophe --version  
  Multi Download:
    i,j     From Serial No. i to Serial No. j
    ,i      From Serial No. 1 to Serial No. i 
    i,      From Serial No. i to serial no 25
    i,j,... Multiple Serial Numbers

**Comment by alyakhtar** [comment]
Please update first and then try. Current version is 2.0.4
