### ISSUE TITLE
BitTorrent or uTorrent should be mentioned as dependencies in readme.md, too

### ISSUE THREAD

**Issue by Tset-Noitamotua** [alyakhtar/Katastrophe#2]
I expected it to work without additional tools but ...

``` shell
Enter torrent No. to download or m for more or b for back or e to exit :  6

Please Install/Run BitTorrent or uTorrent
```

This should be mentioned in readme.md, too ;-)

**Comment by pedrokoblitz** [comment]
I have transmission installed and got a:

raise SSLError(e)
    requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL
    routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by alyakhtar** [comment]
@Tset-Noitamotua I was thinking of doing it in the next version...anyhow will add it to readme.

**Comment by alyakhtar** [comment]
@pedrokoblitz, I am not sure why this is happening, I tested it on my friends machine and it was working perfectly. May transmission is not set as the default the application for magnetic links....i am not sure though.
